import Foundation

/// Centralizes user-facing Chinese copy used by the initial application shell.
enum AppCopy {
    static let appName = "EH 阅读器"
    static let searchTitle = "搜索"
    static let readerTitle = "阅读"
    static let settingsTitle = "设置"
    static let searchPlaceholder = "输入关键词"
    static let searchButtonTitle = "搜索"
    static let searchEmptyTitle = "开始搜索"
    static let searchEmptyMessage = "输入关键词，或直接搜索浏览首页结果。"
    static let searchLoadingTitle = "正在加载"
    static let searchFiltersTitle = "筛选"
    static let searchHiddenCategoriesTitle = "隐藏分类"
    static let searchAdvancedTitle = "高级搜索"
    static let searchBrowseExpunged = "包含已清退图库"
    static let searchRequireTorrent = "需要种子"
    static let searchMinimumPages = "最少页数"
    static let searchMaximumPages = "最多页数"
    static let searchMinimumRating = "最低评分"
    static let searchAnyRating = "不限评分"
    static let searchDisableLanguageFilter = "忽略语言过滤"
    static let searchDisableUploaderFilter = "忽略上传者过滤"
    static let searchDisableTagFilter = "忽略标签过滤"
    static let searchPreviousPage = "上一页"
    static let searchNextPage = "下一页"
    static let searchNoResultsTitle = "没有结果"
    static let searchNoResultsMessage = "可以调整关键词或筛选条件后重试。"
    static let readerEmptyTitle = "尚未打开图库"
    static let readerEmptyMessage = "从搜索结果或图库详情进入阅读器后，这里会显示图片页面。"
    static let settingsMessage = "账号、阅读偏好和缓存策略会在后续阶段补齐。"
}
